### ISSUE TITLE
Launching Gauge specs/scenarios from code

### ISSUE THREAD

**Issue by akurkin** [BugDiver/gauge-ts#114]
Hi,
this is not a bug or feature request (yet).

Is it feasible in a current setup to launch Gauge specs/scenarios bypassing CLI altogether?

Example:
1. "app" receives command to execute specific Gauge test
2. App shells out execution of Gauge test via CLI "gauge run specs/10-my-scenario.md:22"
3. Collects report

I was wondering if instead of shelling out to command line it's possible to use GaugeRuntime and execute scenarios *within existing app* and then operate with reports on a code level?

Any pointers on how to do it are greatly appreciated, thank you for all the hard work on this project <3

**Comment by BugDiver** [comment]
@akurkin The `gauge-ts` is a plugin for gauge. It executes the typescript code which is related to the gauge specs when Gauge requests it to do it. It can't work standalone.
Gauge itself is a CLI tool, so bypassing the CLI might not be possible.
