### ISSUE TITLE
Support for upcoming Cucumber 7.x

### ISSUE THREAD

**Issue by x80486** [BugDiver/gauge-ts#120]
## Is your feature request related to a problem? Please describe.

I was trying the upcoming Cucumber 7.x (now "located at" `@cucumber/cucumber`) and `gauge-ts` was looking for the previous version.

## Describe the solution you'd like

To work towards the newer version.

**Comment by BugDiver** [comment]
@x80486 This is s Plugin for [`Gauge`](gauge.org) Acceptance testing tool. It does/will not work with cucumber.

**Comment by x80486** [comment]
Ha! I'm getting old...this was for `cucumber-js-tsflow` :rofl:
