### ISSUE TITLE
Failed to start gauge API: Timed out connecting to 127.0.0.1:*

### ISSUE THREAD

**Issue by nastyanahrebna** [BugDiver/gauge-ts#29]
**Describe the bug**
Can't run specs

**To Reproduce**
1. gauge install ts
2. gauge init ts
3. npm install
4. gauge run specs

**Expected behavior**
Running specs

**Screenshots**
![image](https://user-images.githubusercontent.com/20207168/71451616-ad99f000-2782-11ea-8681-b34204db3e65.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Gauge and plugin version  1.0.6
 - Node version v12.13.1
 - Npm version 6.13.2

**Additional context**
 - VS Code Version : 1.41.1
 - Gauge VS Code Plugin Version : 0.0.11

**Comment by BugDiver** [comment]
@nastyanahrebna  Thanks for reporting the issue. Will look into it soon

**Comment by BugDiver** [comment]
@nastyanahrebna Sorry for not be able to look into earlier. Now I'm able to replicate this issue and I'm looking into it. Will try my best to fix it ASAP.

**Comment by BugDiver** [comment]
The Fix is available in v0.0.4
